# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('storage_path', models.TextField(default='apks/aebc55d7-aa80-4a2d-827b-07192302632d')),
                ('apk', models.FileField(upload_to='apks/aebc55d7-aa80-4a2d-827b-07192302632d')),
                ('description', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
